---

- hosts: all
  become : true
  tasks:    

  - name: install updates all (CentOs)
    tags: always
    dnf:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "CentOS"  

- hosts: web_servers
  become: true
  tasks:    
   
  - name: install apache and php for CentOS servers
    tags: apache,httpd,centos
    dnf:
       name:
         - httpd
         - php
       state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644     


- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb (CentOs)
    tags: centos,db,mariadb
    dnf:
       name: mariadb 
       state: latest
    when: ansible_distribution == "CentOS" 

- hosts: file_servers
  become: true
  tasks:
          
  - name: install samba package (CentOs)
    tags: samba  
    package:
       name: samba
       state: latest         

